In [1]:
import numpy as np

In [2]:
english_score = np.array([55, 89, 76, 65, 48, 70])
math_score = np.array([60, 85, 60, 68, np.nan, 60])
chinese_score = np.array([65, 90, 82, 72, 66, 77])

In [3]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略？
print("英文科平均＝", np.mean(english_score))
print("英文科最大值＝", np.max(english_score))
print("英文科最小值＝", np.min(english_score))
print("英文科標準差＝", np.std(english_score))
print("數學科平均＝", np.nanmean(math_score))
print("數學科最大值＝", np.nanmax(math_score))
print("數學科最小值＝", np.nanmin(math_score))
print("數學科標準差＝", np.nanstd(math_score))
print("國文科平均＝", np.mean(chinese_score))
print("國文科最大值＝", np.max(chinese_score))
print("國文科最小值＝", np.min(chinese_score))
print("國文科標準差＝", np.std(chinese_score))

英文科平均＝ 67.16666666666667
英文科最大值＝ 89
英文科最小值＝ 48
英文科標準差＝ 13.433995020924426
數學科平均＝ 66.6
數學科最大值＝ 85.0
數學科最小值＝ 60.0
數學科標準差＝ 9.707728879609279
國文科平均＝ 75.33333333333333
國文科最大值＝ 90
國文科最小值＝ 65
國文科標準差＝ 8.825468196582484


In [4]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差？
math_score[4]=55
print(math_score)
print("補考後數學科平均＝", np.mean(math_score))
print("補考後數學科最大值＝", np.max(math_score))
print("補考後數學科最小值＝", np.min(math_score))
print("補考後數學科標準差＝", np.std(math_score))

[60. 85. 60. 68. 55. 60.]
補考後數學科平均＝ 64.66666666666667
補考後數學科最大值＝ 85.0
補考後數學科最小值＝ 55.0
補考後數學科標準差＝ 9.860132971832694


In [5]:
#3. 用補考後資料找出與國文成績相關係數最高的學科？ ANS：英文
x = np.array([english_score, math_score, chinese_score]).reshape(3, 6)
x

array([[55., 89., 76., 65., 48., 70.],
       [60., 85., 60., 68., 55., 60.],
       [65., 90., 82., 72., 66., 77.]])

In [6]:
np.corrcoef(x)

array([[1.        , 0.7855563 , 0.97792828],
       [0.7855563 , 1.        , 0.74056803],
       [0.97792828, 0.74056803, 1.        ]])